config/routes.rb
Rails.application.routes.draw do
  resources :smples
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/smple.rb
class Smple < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/smples_controller.rb
class SmplesController < ApplicationController
  before_action :set_smple, only: [:show, :edit, :update, :destroy]

  # GET /smples
  # GET /smples.json
  def index
    respond_to do |format|
      format.html
      format.js { render :action => 'index' }
    end
    @smples = Smple.all
    record_relation = Smple.all
    #record_relation = Smple.where('grp == "B"')
    @xcords = helpers.get_x_coordinates(record_relation)
    @ycords = helpers.get_y_coordinates(record_relation)
    @heights = helpers.height_coordinates(record_relation)
    @classnames = helpers.set_class(record_relation)
    @xlabels = helpers.get_x_label(record_relation)
    @xlabelpos = helpers.get_x_label_pos(record_relation)
    @legclass = helpers.set_leg_class(record_relation)
    @legname = helpers.set_leg_label(record_relation)
  end

  # GET /smples/1
  # GET /smples/1.json
  def show
  end

  # GET /smples/new
  def new
    @smple = Smple.new
  end

  # GET /smples/1/edit
  def edit
  end

  # POST /smples
  # POST /smples.json
  def create
    @smple = Smple.new(smple_params)

    respond_to do |format|
      if @smple.save
        format.html { redirect_to smples_url, notice: 'Smple was successfully created.' }
        format.json { render :show, status: :created, location: @smple }
      else
        format.html { render :new }
        format.json { render json: @smple.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /smples/1
  # PATCH/PUT /smples/1.json
  def update
    respond_to do |format|
      if @smple.update(smple_params)
        format.html { redirect_to @smple, notice: 'Smple was successfully updated.' }
        format.json { render :show, status: :ok, location: @smple }
      else
        format.html { render :edit }
        format.json { render json: @smple.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /smples/1
  # DELETE /smples/1.json
  def destroy
    @smple.destroy
    respond_to do |format|
      format.html { redirect_to smples_url, notice: 'Smple was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_smple
      @smple = Smple.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def smple_params
      params.require(:smple).permit(:par1, :par2, :grp)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/smples_helper.rb
module SmplesHelper

  
#########    percent_position
#
#
#
#
#
def percent_position(percent_array)
  i=0
  dataPos=[0]
    while i < (percent_array.length-1)
    dataPos[i+1]=percent_array[0..i].sum
    i+=1
    end
  return dataPos
end




###########   height_position
#
#
#
#
#
def height_coordinates(record_relation)
  return_array=[]
  tmpArry=[]
  tmpHash = get_param_percentage(record_relation)
  tmpHash.each{|x,y| 
    return_array += y.values
    }
  return return_array
end




######## get_param_percentage
#
# goal here is to return a hash
#   where each par1 value
#  matches a hash with
#   a breakdown of the percentage of
#        par2 values
#
#
def get_param_percentage(record_relation)
  params=record_relation.map{|x| x.par1}.uniq
  return_hash = {}
  params.each{|p|
    tmpHash = {}
    tmpReltn = record_relation.where(par1: p)
    tmpParams = tmpReltn.map{|x| x.par2}.uniq
      tmpParams.each{|q|
            dubTmpReltn = tmpReltn.where(par2: q)
            tmpPerc = (dubTmpReltn.length.to_f/tmpReltn.length.to_f)*100
            tmpHash[q] = tmpPerc 
      }
    return_hash[p] = tmpHash
  }
  return return_hash
end




########get_stat_values
#
#
#
#
#
def get_stat_values(record_relation)
  return_array=[]
  params=record_relation.map{|x| x.par1}.uniq
  params.each{|p| 
    tmpReltn = record_relation.where('par1 == ' + p.to_s)
    return_array += [p,tmpReltn.map{|x|x.par2}.sum,tmpReltn.map{|x| x.par2}.length]
  }
  return return_array
end





######get_stat_avg
#    returns a hash showing
#       each par 1 value
#          with its average par 2
#             value
def get_stat_avg(record_relation)
  return_array=[]
  tmpArry=get_stat_values(record_relation)
  i=0
  ix=tmpArry.length/3
    while i < ix
    return_array += [tmpArry[i*3],tmpArry[i*3+1]/tmpArry[i*3+2]]
    i+=1
    end
  return_hash = Hash[return_array.each_slice(2).to_a]
  return return_hash
end
 





########get_y_coordinates
#
#   returns an array
#     of y coordinates
#
#
#
def get_y_coordinates(record_relation)
  return_array=[]
  tmpArry=[]
  tmpHash = get_param_percentage(record_relation)
  tmpHash.each{|x,y| 
    tmpArry = y.values
    return_array += percent_position(tmpArry)
    }
  return return_array
end



#######get_par2_legend
#
#   returns an array
#     with the names of par 2 values
#   in same order as get_y_coordinates
#
def get_par2_legend(record_relation)
  return_array=[]
  tmpArry=[]
  tmpHash = get_param_percentage(record_relation)
  tmpArry = tmpHash.keys
  tmpArry.each{|x| 
    return_array += tmpHash[x].keys
    }
  return return_array
end





def get_x_label(record_relation)
  return_array=[]
  tmpArry=[]
  tmpHash = get_param_percentage(record_relation)
  tmpArry = tmpHash.keys.sort
  tmpArry.each{|x| return_array.push(x.to_s)}
  return return_array
end


def get_x_label_pos(record_relation)
  return_array=[]
  tmpArry=[]
  tmpHash = get_param_percentage(record_relation)
  return_array = tmpHash.keys.sort
  return return_array
end


#########get_x_coordinates
#
#
#
#
#
#
def get_x_coordinates(record_relation)
  i=0
  tmpArry=[]
  return_array=[]
  someArry=[]
  tmpHash = get_param_percentage(record_relation)
  tmpArry=tmpHash.keys
  tmpArry.each{|x| someArry.push(tmpHash[x].length)}
    while i < tmpArry.length
    return_array += [tmpArry[i]]*someArry[i]
    i += 1
    end
  return return_array
end




#######set_class
#
#
#    returns array of class names
#       for each par 2 value
#     in same order as xcord and ycord
#
def set_class(record_relation)
  return_array=[]
  tmpArry=[]
  tmpHash = get_param_percentage(record_relation)
  tmpHash.each{|x,y| 
    tmpArry += y.keys
    }
  tmpArry.each{|x| return_array.push("par2"+x.to_s.gsub(/\.5/,'x5').gsub(/\.0/,'')
)}
  return return_array
end




def set_leg_label(record_relation)
  flotArry = []
return_array = []
  tmpArry = set_class(record_relation)
  tmpArry.each{|x| flotArry.push(x.gsub(/par2/,'').gsub(/x/,'.').to_f)}
  return_array = flotArry.uniq.sort.to_s 
  return return_array
end




def set_leg_class(record_relation)
  burnArry = []
  flotArry = []
return_array = []
  tmpArry = set_class(record_relation)
  tmpArry.each{|x| flotArry.push(x.gsub(/par2/,'').gsub(/x/,'.').to_f)}
  burnArry = flotArry.uniq.sort
  burnArry.each{|x| return_array.push("par2"+x.to_s.gsub(/\.5/,'x5').gsub(/\.0/,''))}
  return return_array
end






end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StatPlot3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/smples/_form.html.erb
<%= form_with(model: smple, local: true) do |form| %>
  <% if smple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(smple.errors.count, "error") %> prohibited this smple from being saved:</h2>

      <ul>
      <% smple.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :par1 %>
    <%= form.text_field :par1, id: :smple_par1 %>
  </div>

  <div class="field">
    <%= form.label :par2 %>
    <%= form.text_field :par2, id: :smple_par2 %>
  </div>

  <div class="field">
    <%= form.label :grp %>
    <%= form.text_field :grp, id: :smple_grp %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/smples/edit.html.erb
<h1>Editing Smple</h1>

<%= render 'form', smple: @smple %>

<%= link_to 'Show', @smple %> |
<%= link_to 'Back', smples_path %>

app/views/smples/index.html.erb
<div>
 <%= javascript_tag do -%>
    var stuff = <%= @ycords %>;
    var duff = <%= @xcords %>;
    var rectheights = <%= @heights %>; 
    var xlabelpos = <%= @xlabelpos %>;
    var xlabels = <%= raw @xlabels %>;
    var classnames = <%= raw @classnames %>;
    var legclass = <%= raw @legclass %>;
    var leglabel = <%= raw @legname %>;    
  <%- end -%>
</div>

<p id="notice"><%= notice %></p>
<%= link_to 'New Smple', new_smple_path %>
<h1>Smples</h1>

<table>
  <thead>
    <tr>
      <th>Par1</th>
      <th>Par2</th>
      <th>Grp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @smples.each do |smple| %>
      <tr>
        <td><%= smple.par1 %></td>
        <td><%= smple.par2 %></td>
        <td><%= smple.grp %></td>
        <td><%= link_to 'Show', smple %></td>
        <td><%= link_to 'Edit', edit_smple_path(smple) %></td>
        <td><%= link_to 'Destroy', smple, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<table>
  <thead>
    <tr>
      <th>XCords</th>
      <th>YCords</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <% @xcords.each do |cord| %>
        <td><%= cord %></td>
         <% end %>
      </tr>
      <tr>
        <% @ycords.each do |cord| %>
        <td><%= cord %></td>
         <% end %>
      </tr>


  </tbody>
</table>

<%= link_to 'New Smple', new_smple_path %>

<%= javascript_tag do %>
  window.smplesURL = "<%= j smples_url %>";
  window.smples = <%= raw @ycords %>;
<% end %>

app/views/smples/new.html.erb
<h1>New Smple</h1>

<%= render 'form', smple: @smple %>

<%= link_to 'Back', smples_path %>

app/views/smples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Par1:</strong>
  <%= @smple.par1 %>
</p>

<p>
  <strong>Par2:</strong>
  <%= @smple.par2 %>
</p>

<p>
  <strong>Grp:</strong>
  <%= @smple.grp %>
</p>

<%= link_to 'Edit', edit_smple_path(@smple) %> |
<%= link_to 'Back', smples_path %>